### ISSUE TITLE
Unable to catch errors

### ISSUE THREAD

**Issue by elmarti** [IagoLast/qrcodejs#1]
Hi, when the '_onMediaStreamError' is invoked, the code simply logs the error to the console and there is no way of catching it to display a message to the user. Do you have any advice, or should I have a look into it. 

Thanks!

**Comment by IagoLast** [comment]
yeah! you are right. I see two different solutions here:

1) Passing the mediaStreamError as a callback function to the function constructor


2) When a mediaStreamError is thrown, call the generic onError function

```javascript
_onMediaStreamError(e) {
  console.error(e);
  this.onError(e); 
}
```


The second options may do the work, what do you think?

**Comment by elmarti** [comment]
Great! That worked for me, do you want me to commit it? I'm just going to finish implementing to see if I find any other issues

**Comment by IagoLast** [comment]
👍  feel free to create a PR

**Comment by IagoLast** [comment]
No PR? I think that ir could be a good fix

**Comment by elmarti** [comment]
I've made one! I think.. this is my first attempt haha

**Comment by elmarti** [comment]
https://github.com/IagoLast/qrcodejs/pull/3

**Comment by IagoLast** [comment]
next time create a different PR for each issue :P

**Comment by elmarti** [comment]
ok, sorry about that
