### ISSUE TITLE
Canvas does not render without set video heights

### ISSUE THREAD

**Issue by elmarti** [IagoLast/qrcodejs#2]
Sorry to open another issue, but it's separate! I was unsure for a while, but it seems that the following block 

```
{
    key: '_onAnimationFrameRequested',
    value: function _onAnimationFrameRequested() {
      if (this._stopped) {
        return;
      }
      this._context.drawImage(this._video, 0, 0, this._width, this._height);
      var frame = this._context.getImageData(0, 0, this._width, this._height);
      this._decode(frame);
      requestAnimationFrame(this._onAnimationFrameRequested.bind(this));
    }

```
If you don't set the height on the video using the height and width tags, this._width and this._height are undefined, causing the following error 
`qrcode.js:6362 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.(…)`
 
This was fixed once I set them, I can provide a fix if you want it

**Comment by IagoLast** [comment]
height and width are initialized here:

```javascript
    // Initialize attributes
    this._video = this._createVideoElement(videoSelector)
    this._width = this._video.width;
    this._height = this._video.height;
```

I don't know why they are undefined S:

Feel free to open a pull request if you have a possible solution. Thx for helping.

**Comment by elmarti** [comment]
I will do, one option could be to default them to something if null, I'm not sure if the height is critical for the program to run though, ie: 
```
    this._width = this._video.width || 100;
    this._height = this._video.height || 100;
```

**Comment by elmarti** [comment]
Just fixing this now - the clientHeight attribute takes the actual size of the element, rather than the assigned height. 


```
   this._width = this._video.clientWidth;
   this._height = this._video.clientHeight;
```

**Comment by IagoLast** [comment]
But video values are initialized here:

```javascript
_createVideoElement(videoSelector) {
    if (videoSelector) {
      return document.querySelector(videoSelector);
    } else {
      let video = document.createElement('video');
      video.setAttribute('width', this._defaultWidth);
      video.setAttribute('height', this._defaultHeight);
      return video;
    }
  }

```

**Comment by elmarti** [comment]
For me because I've put a selector, it returns before it reaches that code

**Comment by IagoLast** [comment]
so you are using a custom video right?

the code should use the video width and height.

**Comment by elmarti** [comment]
The issue for me is that the height and width are controlled by the CSS so they are not set using the html attributes height and width, meaning they're undefined at: 

```
    // Initialize attributes
    this._video = this._createVideoElement(videoSelector)
    this._width = this._video.width;
    this._height = this._video.height;
```
eg:

`<video class="video_control" id="video"></video>
`

**Comment by elmarti** [comment]
I guess, alternatively I could do the original solution, but like this: 

```
   this._width = this._video.width || this._defaultWidth;
   this._height = this._video.height || this._defaultHeight;
```
